services:
  - type: web
    name: her-health-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    workingDir: backend
  - type: web
    name: her-health-frontend
    env: static
    buildCommand: ""
    staticPublishPath: frontend
